development:
  bucket: goddamnyouryan_development
  access_key_id: AKIAJ2VXOJBAKFYA6H4Q
  secret_access_key: <%= ENV['GODDAMNYOURYAN_S3_SECRET_ACCESS_KEY'] %>

test:
  bucket: myapptest
  access_key_id: AKIAJ2VXOJBAKFYA6H4Q
  secret_access_key: <%= ENV['GODDAMNYOURYAN_S3_SECRET_ACCESS_KEY'] %>

production:
  bucket: goddamnyouryan_production
  access_key_id: AKIAJ2VXOJBAKFYA6H4Q
  secret_access_key: <%= ENV['GODDAMNYOURYAN_S3_SECRET_ACCESS_KEY'] %>
